### ISSUE TITLE
Color Combiner/Clamping issues on various materials

### ISSUE THREAD

**Issue by MelonSpeedruns** [HarbourMasters/2ship2harkinian#188]
### Update:
As of #472 a temporary workaround has been put in place causing much less things to look wrong. If you see anything else not documented here please continue adding screenshots

---

![image](https://github.com/HarbourMasters/2ship2harkinian/assets/6260159/6b59e3e2-deaa-4cd1-8221-02205e50e8d6)

![image](https://github.com/HarbourMasters/2ship2harkinian/assets/6260159/5459da39-99f2-4404-89a7-7f6cc5b9fed7)

**Comment by garrettjoecox** [comment]
After the temporary workaround, this is what the shield looks like now:

## Correct

![image](https://github.com/HarbourMasters/2ship2harkinian/assets/7316699/9db7340e-8fa1-4319-aee5-bd78709f90e5)

## 2Ship

![image2](https://github.com/HarbourMasters/2ship2harkinian/assets/7316699/3f562dee-f9af-4726-b665-baf98be35679)

**Comment by garrettjoecox** [comment]
This was mostly fixed by https://github.com/Kenix3/libultraship/pull/620

The last remaining known issue is with the Song of Soaring. Will continue in a separate issue
