### ISSUE TITLE
Interpolation snapping artifact on cutscenes

### ISSUE THREAD

**Issue by PurpleHato** [HarbourMasters/2ship2harkinian#215]
The camera encounters a noticeable artifact during new areas cutscenes or any cinematic shots that abruptly alter its position
It seems that the camera being suddenly teleported or snapped from one location to another, causing a rollback artifact due to interpolation

https://github.com/HarbourMasters/2ship2harkinian/assets/47987542/e3f93e48-043e-47a4-b55b-9bf3f1a37de1

**Comment by garrettjoecox** [comment]
Fixed by #479
