### ISSUE TITLE
Sakon's Hideout Low FPS after Completing

### ISSUE THREAD

**Issue by MegaMech** [HarbourMasters/2ship2harkinian#306]
After using noclip to skip to the end of Sakon's hideout. The game fps/audio is kinda glitchy. Might be something wrong here. I didn't do any of the pre-requesites to enter the hideout I just noclipped in.

Like even after leaving the game is glitching out. Restarting the game fixed it.

DX11 W10

**Comment by Archez** [comment]
We had a bug regarding frame timing that would impact FPS after a certain amount of play. This has since been fixed with the release of Satoko 1.1.x
There haven't been any other reports specifically regarding Sakon's Hiedout, so I'm going to consider this resolved.
