### ISSUE TITLE
Juggler has incorrect ball texture

### ISSUE THREAD

**Issue by garrettjoecox** [HarbourMasters/2ship2harkinian#334]
The juggler's ball texture is incorrect, depending on the angle it seems to be pulling from another source:
2Ship:
<img width="65" alt="Screenshot 2024-05-08 at 2 51 44 PM" src="https://github.com/HarbourMasters/2ship2harkinian/assets/7316699/e7ad0e69-9f01-4f8f-90f5-76bb079f52b5">
<img width="115" alt="Screenshot 2024-05-08 at 2 51 35 PM" src="https://github.com/HarbourMasters/2ship2harkinian/assets/7316699/de0be1fb-bf62-4f16-8d2c-dab5d3803f81">

AngryLion:
<img width="106" alt="Screenshot 2024-05-08 at 2 50 59 PM" src="https://github.com/HarbourMasters/2ship2harkinian/assets/7316699/e334e73d-03b6-4105-8944-f409f4b5867f">

Upon inspection of the DL, the texture is registered as `G_IM_SIZ_8b` both in decomp and in our own XMLs, but when inspecting via the GFX debugger, it seems to think it should have the size of `G_IM_SIZ_16b`

DL from decomp
<img width="721" alt="Screenshot 2024-05-08 at 2 50 24 PM" src="https://github.com/HarbourMasters/2ship2harkinian/assets/7316699/9e1de07d-73b8-410b-8ba6-7c4926015707">

DL in GFX Debugger
<img width="1203" alt="Screenshot 2024-05-08 at 2 50 12 PM" src="https://github.com/HarbourMasters/2ship2harkinian/assets/7316699/c82ab966-f8b6-4ea4-a7e0-b04b5c473013">

**Comment by Archez** [comment]
Fixed by the recent color combiner changes in LUS that improved texel 1 handling.
