### ISSUE TITLE
Opaque grate texture in laundry pool

### ISSUE THREAD

**Issue by garrettjoecox** [HarbourMasters/2ship2harkinian#355]
2Ship:
<img width="778" alt="Screenshot 2024-05-10 at 2 25 03 PM" src="https://github.com/HarbourMasters/2ship2harkinian/assets/7316699/cc2c5fa4-0ffd-4762-b486-b1452ce762d9">

AngryLion:
<img width="765" alt="Screenshot 2024-05-10 at 2 25 54 PM" src="https://github.com/HarbourMasters/2ship2harkinian/assets/7316699/ac83fd01-f4c3-4620-8542-6554b1e116f1">

Also strange, is that on the other side of the creek there is another grate texture that is very similar, and rendered correctly on 2ship:
<img width="774" alt="Screenshot 2024-05-10 at 2 26 53 PM" src="https://github.com/HarbourMasters/2ship2harkinian/assets/7316699/3ab2bf2d-3e3f-4653-ab42-dea218f0b56a">

**Comment by Archez** [comment]
Fixed by the recent color combiner changes in LUS that improved texel 1 handling.
