### ISSUE TITLE
Finish implementing Kaleido Dungeon maps

### ISSUE THREAD

**Issue by Archez** [HarbourMasters/2ship2harkinian#409]
The Kaleido dungeon maps, similar to OoT, use palette tables to show/hide/change the look of rooms.

In 2Ship, there are two problems that need to be addressed:
* Texture caches need to be busted when the palette tables are changed (we've done this already in SoH and can use that as reference).
  * There is an extra level of cache busting that we need to be mindful of if we want to properly enable HD support. SoH also has this implemented, but it is worth noting that no one has really produced an actual mod taking advantage of this.
* Our Fast3D implementation supports only two palette tables, but the kaleido map leverages three palette tables. This would require reworking on the palette handlers on the Fast3D side.
  * Additionally, the cache busting needs to account for the extra palette possibilities.

### Example of the current state of dungeon maps.
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/13861068/0010e816-975f-4f45-be08-d53cfc8a922a)

**Comment by louist103** [comment]
Resolved by #653. Didn't auto close.
