### ISSUE TITLE
Clocktower gears move erratically [Mac - Release mode]

### ISSUE THREAD

**Issue by Archez** [HarbourMasters/2ship2harkinian#437]
The clock tower gears and potentially the smaller ones elsewhere will periodically spin very fast. This appears to maybe be a math precision error possibility related to compiler optimizations when running in release mode on Mac.

https://github.com/HarbourMasters/2ship2harkinian/assets/13861068/6e1b636d-9ef4-4cea-9e6c-ff890bf00958

**Comment by tdh236** [comment]
Hey, just checking to see if there's a fix for this yet. Thanks
