### ISSUE TITLE
Removing a transformation mask sets flags that prevents learning opening for Goron Lullaby[Linux]

### ISSUE THREAD

**Issue by sitton76** [HarbourMasters/2ship2harkinian#490]
EDIT: I initially thought this issue was related to the use of Debug mode, but after release additional users reported having this problem. If I can find more details I will edit them into this post.

- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
After messing around and seeing a tip from user Bobafett. It seems on the Linux release builds for 2ship removing a transformation mask and going back to Human Link sets 3 arbitrary flags in the 24th row in weekEventReg.

Two of these set flags relate to the Goron Elder(specifically 4 and 6) and prevents you from learning his song. These flags reset on reverting time so if you manage to free him without reverting back to human form it should work as intended.

Having fast transformations enabled seems to bypass this issue.

### Can you reproduce? If so please list the steps:
- [x] Yes, here are the steps to reproduce the bug:
1. Run the Linux appimage of 1.0.0 2ship.
2. Put on a transformation mask, then remove it.(This sets 3 arbitrary flags in the 24th row of weekEventReg)
3. Attempt to learn the opening to the Goron Lullaby.

### System Information:
- OS: Garuda Linux Bird of Prey
- GFX Backend: OpenGL
- Game Version: 1.0.0
- Rom Version: NTSC US Gamecube

**Comment by BobaFrett** [comment]
I am experiencing a similar issue learning the Goron Lullaby, but I have not enabled debug mode. However, I am playing on a save imported from the Zelda 64 Recomp for what it's worth.

Playing on a Steam Deck OLED using a N64 USA ROM

**Comment by TheChiefu** [comment]
I'm playing on a fresh file with Auto Save, Start Menu Save, and Fast Text on and have run into this issue.

**Comment by sitton76** [comment]
Ok so after messing around I can verify it is actually not related to Debug mode like I initially thought, not sure what the cause is currently but ill continue testing to see if I can find a root cause...I will also edit my OP to reflect this.

**Comment by BobaFrett** [comment]
Ok, so I was able to work around this issue by editing some flags on the save. I started in the Goron Village, then went into the Save Editor, selected the Flags tab, then chose weekEventReg from the dropdown. From there, I unchecked boxes 4 & 6 on Row 24, which reset the "Spoke to Goron Elder Twice" and "Goron Elder Taught Lullaby Intro" flags (both were checked). 

For reference, I came across this list of flags while digging into things: https://tcrf.net/Proto:The_Legend_of_Zelda:_Majora%27s_Mask/Debug_Version/Event_Editor

Still not sure what caused the flag mixup, but I was able to learn the lullaby and progress from there!

**Comment by Aether89** [comment]
I also had the issue with Persistent Owl save and **Pause Menu Save** enabled, I disabled them and played the song of time to reset the cycle and i was able to learn the song on the new cycle, but not on the previous one even by disabling them.

**Comment by sitton76** [comment]
> Ok, so I was able to work around this issue by editing some flags on the save. I started in the Goron Village, then went into the Save Editor, selected the Flags tab, then chose weekEventReg from the dropdown. From there, I unchecked boxes 4 & 6 on Row 24, which reset the "Spoke to Goron Elder Twice" and "Goron Elder Taught Lullaby Intro" flags (both were checked).
> 
> For reference, I came across this list of flags while digging into things: https://tcrf.net/Proto:The_Legend_of_Zelda:_Majora%27s_Mask/Debug_Version/Event_Editor
> 
> Still not sure what caused the flag mixup, but I was able to learn the lullaby and progress from there!

Thanks for the info, are you by chance running the Linux appimage version of the game? Because I think I found the cause.

Those flags you mentioned get set by taking off a transformation mask(so for example going from Deku -> Human Link.) this only seems to trigger on the Linux appimage build. I have also tested the Windows build via WINE myself and asked one other to test it and it did not trigger on that build.

So maybe a compiler optimization is causing this?

**Comment by BobaFrett** [comment]
Interesting... Yes, I'm running the Linux appimage.

**Comment by Aether89** [comment]
i am also using the Linux appimage.

**Comment by kristianfreeman** [comment]
> Ok, so I was able to work around this issue by editing some flags on the save. I started in the Goron Village, then went into the Save Editor, selected the Flags tab, then chose weekEventReg from the dropdown. From there, I unchecked boxes 4 & 6 on Row 24, which reset the "Spoke to Goron Elder Twice" and "Goron Elder Taught Lullaby Intro" flags (both were checked).
> 
> For reference, I came across this list of flags while digging into things: https://tcrf.net/Proto:The_Legend_of_Zelda:_Majora%27s_Mask/Debug_Version/Event_Editor
> 
> Still not sure what caused the flag mixup, but I was able to learn the lullaby and progress from there!

This fix worked for me too. Playing on Steam Deck OLED. Thanks for documenting this!

**Comment by Archez** [comment]
Fixed by Rika Bravo (1.0.1)
