### ISSUE TITLE
Clock UI Sun/Moon Icon Stays Still Then Jumps Into Position

### ISSUE THREAD

**Issue by TSEG6** [HarbourMasters/2ship2harkinian#503]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
The clock number is moving as expected but the sun/moon icon is not, it loves to stay still and then jump into postion after a few seconds.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

1. Get into the game where the clock UI is visible
2. Wait and see the sun/moon icon not move then jump into position

### Expected behavior:
The Sun/Moon icon should move the same way as the number above it.

### Screenshots or videos:

https://github.com/HarbourMasters/2ship2harkinian/assets/44306826/25f68c4b-5476-4216-9748-301445f4abaf

https://github.com/HarbourMasters/2ship2harkinian/assets/44306826/845a1089-b05c-48a1-b4e6-49f0cde1b2af

### System Information:
- OS: Windows 11
- GFX: DirectX
- Game Version: 1.0.0
- Rom Version: US 1.0

**Comment by TheTrueShadow** [comment]
This seems to work fine for me it could be your ROM maybe

**Comment by garrettjoecox** [comment]
This actually seems to be attributed to moving the clock in the HUD editor, if you set the clock back to the vanilla position it no longer jumps

**Comment by TheTrueShadow** [comment]
Oh I see now I had my stuff in vanilla positioning so thats why it worked for me

**Comment by TSEG6** [comment]
Yeah, that's the issue, switching it back fixes it.

**Comment by Archez** [comment]
Fixed by Rika Bravo (1.0.1)
