### ISSUE TITLE
Sky Changes Weirdly Sometimes When Hour Changes

### ISSUE THREAD

**Issue by TSEG6** [HarbourMasters/2ship2harkinian#504]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
When the in game hour changes (early/late hours) the sky suddenly changes (I think rotation?)

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

1. Go somewhere where the sky can be seen
2. Wait for an hour change (I think first/last two hours of the day)
3. See the bug

### Expected behavior:
The sky should not do whatever it's doing, it should be smoothly rotating and fading

### Screenshots or videos:

https://github.com/HarbourMasters/2ship2harkinian/assets/44306826/2ad73325-a52e-4c8f-a34a-77426de1fe46

### System Information:
- OS: Windows 11
- GFX Backend: DirectX
- Game Version: 1.0.0
- Rom Version: US 1.0

### Additional Information:
Nothing really

**Comment by louist103** [comment]
Fixed by #719
