### ISSUE TITLE
Pause Saving bug during intro

### ISSUE THREAD

**Issue by Patrick12115** [HarbourMasters/2ship2harkinian#505]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
Pause saving and resetting during the intro respawns you as Human Link instead of Deku Link

### Can you reproduce? If so please list the steps:
- [x] Yes, here are the steps to reproduce the bug:
1. Get to the part of the intro where you gain control of Human Link
2. Use the pause save enhancement and reset the game
3. You will now be in South Clock Town during the first cycle as Human Link instead of Deku Link

### Expected behavior:
Should be Deku Link for the first cycle as you need the bubble to get the Ocarina back.

### System Information:
- OS: Windows 10
- GFX Backend: DirectX
- Game Version: 1.0.0
- Rom Version: MM USA rom 1.0

**Comment by garrettjoecox** [comment]
Fixed by #616
