### ISSUE TITLE
Timer HUD Element does not move

### ISSUE THREAD

**Issue by Sonlen1414** [HarbourMasters/2ship2harkinian#506]
Minigame and Skull Kid Timers appear to not move with any of the Movable options, Hidden hides the timers as expected, and the Scale properly rescales the element, it just cannot be moved with either slider. Tested specifically with the Archery Minigame in Clock Town as well as the Deku Playground, and of course against the Skull Kid.

Linux version on Steam Deck if that matters any.

Reproduceable through restarts of game and system.

**Comment by Archez** [comment]
Fixed by Rika Bravo (1.0.1)
