### ISSUE TITLE
Slashing sword disables free camera

### ISSUE THREAD

**Issue by rnp509** [HarbourMasters/2ship2harkinian#508]
I'm not exactly sure if this is a bug, but I don't see why it would be intentional.

**Comment by Patrick12115** [comment]
Can you share a video of this? I cannot seem to reproduce.

**Comment by rnp509** [comment]
Sure.

https://github.com/HarbourMasters/2ship2harkinian/assets/22090416/deefaf69-7d50-449b-88be-ac04e65af3d7

**Comment by rehashedsalt** [comment]
I also get this issue, attaching my 2ship json for review:

[2ship2harkinian.json](https://github.com/HarbourMasters/2ship2harkinian/files/15457903/2ship2harkinian.json)

Can also repro with quick spins, charged spins, untarged airborne jumpslashes, goron punch, zora slash, etc.

**Comment by louist103** [comment]
Fixed by #721
