### ISSUE TITLE
Continual void out/unloading of clocktown area when the final hours cutsene plays.

### ISSUE THREAD

**Issue by Ishtah333** [HarbourMasters/2ship2harkinian#513]
- [X ] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [X ] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:

I was in west clocktown when the final hours countdown started and the clocktower opened and when the cutscene finished i was infinitely falling into the void due to what appeared to be the area fully unloading. I was able to see south clocktown still loaded and used the hover cheat code to fly over there and that area worked fine. The bug only appears the first time the cut scene plays and may or may not be tied to being a deku scrub. It can be replicated in east clocktown, west clocktown and north clocktown, however it does not happen if you are in a building or outside of clocktown when the cutscene triggers.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [X ] Yes, here are the steps to reproduce the bug:
<!--
1. Go to North Clocktown, West Clocktown, or East Clocktown (Must be outside)
2. Wait for the clock to strike midnight on night of the third day for the first time in that save file.
3. The area should unload into a purple void in which you continually loading into, fall and void out.

### Expected behavior:
See above section.

### Screenshots or videos:
N/A although can be provided if required.

### System Information:
- OS: Windows

**Comment by garrettjoecox** [comment]
Thanks for the report! I knew about this but forgot to make a github issue. This is a problem with the "Skip Cutscenes" enhancement

**Comment by thegreatzoidberg** [comment]
I can confirm this also happens during First Cycle with Skip Story Cutscenes at these locations.
- Stock Pot Inn
- Post Office
- Bomb Shop
- Trading Post
- Curiosity Shop
- Clock Town Fairy Fountain
- Deku Scrub Playground
- Mayor's Residence

The alternate Final Hours cutscene inside the sewers/Astral Observatory does not warp you to South Clock Town.

Being any form other than Deku doesn't seem to stop the cutscene warp.

Giving yourself an Ocarina during First Cycle seems to stop the warp completely.

### Steps to reproduce

1. Start new game or remove your Ocarina from an existing save.
2. Turn on Skip Story Cutscenes
3. Be anywhere inside Clock Town other than South Clock Town when Final Hours cutscene triggers.

**Comment by Archez** [comment]
Fixed by Rika Bravo (1.0.1)
