### ISSUE TITLE
Github has broken URL's in Readme

### ISSUE THREAD

**Issue by Nicholas-Steel** [HarbourMasters/2ship2harkinian#517]
Visit https://github.com/HarbourMasters/2ship2harkinian
Scroll down to see the readme contents
Click the Windows link
Get taken to a page saying the download doesn't exist, try this alternative instead.

Also I suspect a lot of people might not know what a Continuous Integration Build _is,_ and would suggest renaming it to "frequently updated in-development release". Include a suggestion to go to the Releases page (include URL) for stable releases.

**Comment by garrettjoecox** [comment]
Fixed by https://github.com/HarbourMasters/2ship2harkinian/pull/511
