### ISSUE TITLE
Play as Kafei Bug

### ISSUE THREAD

**Issue by Patrick12115** [HarbourMasters/2ship2harkinian#518]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
When switching on or off Play as Kafei mode and then putting on and taking of a tranformation mask, Link's skeleton will update, but the fixes for the face and waist still need a scene change, resulting in the face and waist being messed up

### Can you reproduce? If so please list the steps:
- [x] Yes, here are the steps to reproduce the bug:

1. Toggle the play as Kafei enhancement, don't change scenes
2.  Put on and take off any transformation mask
3. Links skeleton will update, but not the face or waist

### Expected behavior:
The skeleton should not change until scene change, or the face and waist should update when the transition happens

### Screenshots or videos:

https://github.com/HarbourMasters/2ship2harkinian/assets/115201185/cf0dcd77-0f0a-4618-872e-9439bfe10e87

### System Information:
- OS: Windows 10
- GFX Backend: DirectX
- Game Version: 1.0.0
- Rom Version: US 1.0

**Comment by Archez** [comment]
Fixed by Rika Bravo (1.0.1)
