### ISSUE TITLE
Debug save settings persisting after disabling debug mode

### ISSUE THREAD

**Issue by Patrick12115** [HarbourMasters/2ship2harkinian#520]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
When you set the debug save to anything, even with debug mode turned off, that settings will still apply to any new save and you must turn it back on and switch it to empty save to create normal saves again.

### Can you reproduce? If so please list the steps:
- [x] Yes, here are the steps to reproduce the bug:

1. Turn on debug mode and change the save file mode to something other than empty save
2. Turn debug mode off
3. Create a new save, it will create a debug save, rather than a normal empty save

### Expected behavior:
With debug turned off, the debug file save settings should not affect creating a new file and it should work like a vanilla new save would.

### System Information:
- OS: Windows 11
- GFX Backend: DirectX
- Game Version: 1.0.0
- Rom Version: US 1.0

**Comment by garrettjoecox** [comment]
Fixed by #643

**Comment by louist103** [comment]
Fixed
