### ISSUE TITLE
Bad Bats actor did not spawn in Day 1 grave. 

### ISSUE THREAD

**Issue by zmarotrix** [HarbourMasters/2ship2harkinian#524]
- [ ] I have checked checked the known issues and searched Github to ensure this issue has not already been reported.

### Description of the inaccuracy:
That bats were missing. The chest spawned upon room load. I have to start a new cycle to see if I can reproduce. I had not done anything unusual in the grave, but I did clip in. Time of Day does not effect this spawn in vanilla.

![image](https://github.com/HarbourMasters/2ship2harkinian/assets/3902321/c11dc4b7-d242-4dcc-a10a-00a3e9c8b61a)

### System Information:
- OS: Windows 10 19045.4412
- GFX Backend: DirectX
- Game Version: English 1.0
- Rom Version: English 1.0

**Comment by louist103** [comment]
Fixed by #724
