### ISSUE TITLE
Hang on launch when non-ascii character in path

### ISSUE THREAD

**Issue by thistle-witch** [HarbourMasters/2ship2harkinian#525]
### Description of the crash:
When launching 2ship when there is a non-ascii character in the path an error message pops up on launch and the game window hangs indefinitely.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this crash
- [x] Yes, here are the steps to reproduce the crash:
    - Place a newly extracted 2ship folder in a path that contains a non-ascii character (example: þ)
    - Generate the o2r files by providing a MM rom
    - Attempt to launch 2ship

### Screenshots or videos:
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/129108882/28e560f1-e65f-4de7-9681-b0176762844f)

### Logs:
No log file was generated

### System Information:
- OS: Windows 11
- GFX Backend: DirectX
- Game Version: 1.0.0 Rika Alfa
- Rom Version: 1.0 NTSC Cartridge dump

**Comment by garrettjoecox** [comment]
Fixed by #743
