### ISSUE TITLE
Save Import not working with special characters / spaces in file path

### ISSUE THREAD

**Issue by sanityormadness** [HarbourMasters/2ship2harkinian#531]
- [✔] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [✔ ] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
FLA save files are not importing. This applies with both files I've used in PJ64 and files I've downloaded from the internet to try.

### Can you reproduce? If so please list the steps:
- [✔] Yes, here are the steps to reproduce the bug:
1. Go to https://drive.google.com/file/d/1vt91mBPItp5pxov9G4nij29XopuNGUcZ/view
2. Download and unzip FLA file.
3. Try and drop it onto save page. Get "Unsupported file dropped, ignoring" message.

### Expected behavior:
Save import successfully.

### Screenshots or videos:
![NotSupportedIgnoring](https://github.com/HarbourMasters/2ship2harkinian/assets/72420323/af04f393-06b3-43f6-a08b-94da5df51da5)

### System Information:
- OS: Windows 10
- GFX Backend: DirectX
- Game Version: 1.0.0
- Rom Version: GC

### Additional Information:
[2 Ship 2 Harkinian.log](https://github.com/HarbourMasters/2ship2harkinian/files/15456852/2.Ship.2.Harkinian.log)

**Comment by garrettjoecox** [comment]
@sanityormadness can you try removing spaces & special characters from the file name?

**Comment by garrettjoecox** [comment]
I was able to get the save imported by removing spaces/special characters from the file path. Closing this out, let me know if that doesn't work for you

**Comment by sanityormadness** [comment]
Okay, yes, that worked. I will point out that the only spaces/special characters in the path were ones because "ZELDA MAJORA'S MASK" is the internal name of the ROM, and I got a message telling me it was unsupported. That still needs fixed, or it's going to trip a lot of people up.

**Comment by garrettjoecox** [comment]
Actually, while it's known I haven't created a github issue to keep track of it so we can just use this one

**Comment by TailsGuy** [comment]
Additionally, the game only imports the save in the first slot.

**Comment by garrettjoecox** [comment]
Fixed by #611
