### ISSUE TITLE
Holding B with fast text enhancement, causes instant text boxes to never advance

### ISSUE THREAD

**Issue by Feli-Heli** [HarbourMasters/2ship2harkinian#533]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
I noticed a “bug” when using the fast text dialogue enhancement. I say “bug” because this is actually how mm works normally, but if you’re hitting the B button every frame, it will cause fast text boxes to never advance (if you start pressing b before the textbox finishes initially), so I recommend fixing that when using the fast text option, so you can just hold b the whole time for every textbox.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

https://github.com/HarbourMasters/2ship2harkinian/assets/108558974/7b91c836-48ea-4a79-a749-5b328280cd48

**Comment by kAuFish** [comment]
I don't wanna hijack ur thread, but a vanilla game feature on "fast text boxes" (ones where an input displays the whole log) have this weird property where if you have a B input the frame the text is over, it won't pull up the sequence to close it. 

Taking a guess here: it's just inputting a B input every frame, so it would cause this bug to happen frame perfectly. It looks exactly like what ur showing here. 

Here's a video describing this https://youtu.be/65cilUmZPSo?si=iThC3-o9V-nseL-4


Edit I'm stupid and saw the pull request that figured this out.
