### ISSUE TITLE
Song of Soaring color combiner issue

### ISSUE THREAD

**Issue by XarceChronus** [HarbourMasters/2ship2harkinian#538]
- [ ] I have checked checked the known issues and searched Github to ensure this issue has not already been reported.

### Description of the inaccuracy:
When flying with the owl song there's pee and black mixed in the feather aura when flying

### Screenshots or videos of 2Ship's behavior:
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/92388626/f0984cbd-6b64-44fc-99e9-6a998f8f4442)

### System Information:
- OS: Windows 10
- GFX Backend: DirectX
- Game Version: 1.0? Not sure
- Rom Version: Same thing?? N64 version

### Additional Information:
Just flyin with my ocarina when I noticed pee is all over my feathers

**Comment by XarceChronus** [comment]
Unrelated but plz add draw distance setting and culling. I dun like how everything culls inside the camera view. The other port did not have this issue.

I understand that project is unrelated and is a dynamic recomp, Just making a request.

**Comment by louist103** [comment]
This is known and is part of #188

**Comment by garrettjoecox** [comment]
This is the last known color combiner issue, opting to re-open this one instead of keeping #188

**Comment by garrettjoecox** [comment]
This was resolved with https://github.com/Kenix3/libultraship/pull/628
