### ISSUE TITLE
Ocarina songs that don't use the A button aren't cancelled by L button when playing with D-pad ocarina

### ISSUE THREAD

**Issue by McBedtime** [HarbourMasters/2ship2harkinian#544]
Reported by Master L on Discord
Currently, when playing the ocarina with the D-pad using the D-pad ocarina option, holding the L button doesn't properly prevent song recognition _if_ the song doesn't use the A button (Song of Soaring, for example). Songs that use the A button are not affected by this.
This issue doesn't occur when playing the ocarina with the buttons that are mapped to the C button inputs

**Comment by Archez** [comment]
Fixed by Rika Bravo (1.0.1)
