### ISSUE TITLE
No .GCN ISO Support Option for Ship2 to extract assets from LoZ Collectors Edition Game. 1.0 US ISO.

### ISSUE THREAD

**Issue by SsjSora** [HarbourMasters/2ship2harkinian#545]
- [ ] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [ ] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
I am completely new to this. I don't really want to discuss it on the discord. So I apologize. I read and it said it "Supports GCN Roms" So But no GCN option because I feel bummed out. I legally own a copy of The Collectors Edition 1.0 on GameCube. And I don't know how to convert the GameCube version into a N64 ROM. Can someone figure this out for me please? Or will Ship2 add a GCN option in the future? All I see is .N64 for now. Will there be a new update to extract the assets from the GameCube versions in the future? Thanks. Or is there a way to convert GameCube games to .N64 format so I can do it that way? Sorry. I apologize. XD Really want to get this up and running. Thanks.

**Comment by Malkierian** [comment]
You need to extract the ROM from the ISO. They're not the same. You can do that all from Dolphin, or you could use https://github.com/Spodi/GCIE-PS if you're on Windows or possibly if you install .Net core and Powershell core on Linux.

**Comment by SsjSora** [comment]
> You need to extract the ROM from the ISO. They're not the same. You can do that all from Dolphin, or you could use https://github.com/Spodi/GCIE-PS if you're on Windows or possibly if you install .Net core and Powershell core on Linux.

Do you know how to do that from Dolphin by chance? Is there a tutorial out there on YouTube that explains the steps? Would like to get this up and running today. Currently got Dolphin installed on my PC. Never done this before, but thank you for letting me know. And I like your avatar pic btw. :)

**Comment by SsjSora** [comment]
> You need to extract the ROM from the ISO. They're not the same. You can do that all from Dolphin, or you could use https://github.com/Spodi/GCIE-PS if you're on Windows or possibly if you install .Net core and Powershell core on Linux.

Ok ok ok!!! I did it! Got the ROM its self extract from my Legal copy of Collectors Edition and so far no problems!!! Checked YouTube for tutorials. THANK YOU!!! :D:D:D 1.0 works well! Thanks!!! :D It works on Ship2. Thank you! :D I used Dolphin! ^_^ I appreciate the help. :D

**Comment by Malkierian** [comment]
> And I like your avatar pic btw. :)

LOL, thanks.

Glad you found a tutorial, I couldn't find one myself. Would you link it here for others to reference?

**Comment by pedrovay2003** [comment]
I'm not the original poster, and I didn't use Dolphin to get my ROMs, but I can post the tutorial I used (found on https://krikzz.com/forum/index.php?topic=5281.0):

Guide to Dumping your Zelda MQ or Zelda Collector's Edition Gamecube discs
--------------

Download:
GC Tool: http://wiki.gbatemp.net/wiki/GC-Tool
TGCtoGCM: http://www.romhacking.net/utilities/1096/

Step 0: Create an iso of your gamecube game
---------------
https://wiki.dolphin-emu.org/index.php?title=Ripping_Games
   - lists the best ways to rip GC discs

Step 1: GC Tool
---------------
1. Open GC-Tool.exe
2. Choose File - Open
3. Change it to look for all files
4. Open your iso file
5. On the right, expand GCMRoot
6. (Zelda Collections)
	- zelda_xxx_dddddd.tgc (xxx is PAL or ENG)
	- majora_xxx_ddddddd.tgc (ddddddd is the date/version)
   (Ocarina MQ)
	- zlj_f.tgc
7. Right click each file above and choose Extract File
8. Save the file (repeat for each of the tgc files listed above
9. Copy the files to the TGCtoGCM folder

Step 2: TGCtoGCM
----------------
10. Hold shift and right click in the TGCtoGCM folder, then choose Open Command Window Here
11. For each TGC file, type this:
	tgctogcm <filename>.tgc <newfilename>.gcm
    and hit return.  Repeat for any tgc files you extracted
12. Close the Command Prompt window
13. Copy the files back to the main folder

Step 3: GC Tool again
----------------
14. Open GC-Tool.exe
15. Choose File - Open
16. Change it to look for all files
17. Open each gcm file
18. On the right, expand GCMRoot
19. Look for any .n64 files
20. Right click and choose Extract File for each (ura is MQ)
21. Repeat for any gcm files you created in Step 2
22. Bonus - extract any .thp files to get movies, like the end credits movie
23. Close GC-Tool.exe

**Comment by SsjSora** [comment]
> > And I like your avatar pic btw. :)
> 
> LOL, thanks.
> 
> Glad you found a tutorial, I couldn't find one myself. Would you link it here for others to reference?

I used this tutorial on from the Dolphin forums from a user named [Axxer] just scroll down till you find their tutorial and follow EXACTLY as they SAY along with this YouTube Tutorial if anyone prefers to use Dolphin. I literally EXTRACTED Majora's Mask and Ocarina of Time 1.0 GCN versions from my US Collectors Edition I backed up MY SELF THROUGH my brother's Wii. "No joke" I think you guys will love this. I had to do my own research. I hope this will help you and others instead of doing of having to do "complicated stuff" etc. Especially if you are a "slow" person/learner like me. Hope this helps! And this is talking about doing it the 'LEGAL WAY GUYS! If you want "ROMS" go ELSEWHERE!!! This is for HELPING PEOPLE GET THE ROMS FROM THEIR OWN LEGALLY OBTAINED GAMES!!! And YES I have tested it on PJ64 and they both work! :D :) Good luck to everyone who uses this tutorial. I'm showing some images to help.

Follow THIS tutorial FIRST off the YouTube... This isn't my channel btw. Give credit to the guy. Follow EXACTLY WHAT THEY DO! Literally, EXACTLY!!! It isn't that hard. Trust me I didn't knew this existed till now. :)

Mod Tutorial: Extracting Game Files and Running Extracted Files with Dolphin by DebugYoshi
https://www.youtube.com/watch?v=plUi3Ak-B98

How to make grab N64 Roms from GCN games or any ROMS in general. Also note, you NEED THIS TOOL HERE IN THE DESCRIPTION... [(tgctogcm.exe)] Download the TGC Tool you will need it to compile it to a N64 Rom from COLLECTORS EDITION when you got everything extracted from Dolphin, make sure you put everything in the SAME FOLDER, including the TGCN program. Go into CMD like normal and type these in. Or you can do it one at a time, "With your PCs username of course. Though I hope you get my drift. lol.  cd "

C:\Users\<username>\Desktop\"
tgctogcm.exe "majora_ENG_091003.tgc" "Majora's Mask.gcm"
tgctogcm.exe "zelda_ENG_090903.tgc" "Ocarina of Time.gcm"

(http://www.mediafire.com/?abi43b3bxjt8n0x) "I tested it my self it's 100% safe." If any of you know how to do this already you need to put the extracted roms named majora_ENG_091003.tgc same with zelda_ENG_090903.tgc <--- "This one is OoT BTW if those who don't know" Sorry I SUCK at making tutorials. LMAO!!! And explaining things...

https://forums.dolphin-emu.org/Thread-gc-the-legend-of-zelda-collector-s-edition?page=2

CREDIT goes to the original person who made the tutorials. I'm just trying to help. I'll post a picture to show you guys the easier way they're explaining.

https://imgur.com/a/WPKpAsj   <----  Tutorial from Dolphin forums. <----- Please use it to your hearts content and BOOK MARK THEIR SITE for future reference if you wish to share. :) In case anyone is curious here is what mine looks like on my folder.

https://imgur.com/a/xIr7nL1 Here is my folder where the MM Rom is I extract from Collectors Edition using the tutorial. Guarantee 100% it works on Ship2. :) I was playing it all day. :3 I reccomend make seperate folder for MM and OoT to put both files in btw to make life easier. :3 Sorry for shit tutorial lol. This is my first one. :( Important put OoT files in OoT folder, same with MM. If you dont want to get confused while converting. What I was trying to say. Sorry. If someone can interpret my shit tutorial I'd appreciate it. lol. I showed images to help. :) I hope this helps anyone, enjoy! :D 


Convert explanation. https://imgur.com/a/m0tEXV5 Though I think pedrovay2003 tutorial is better than mine! XD :D ^_^ Trying to support each other guys! :D :) Thanks pedrovay2003 for explaining it better than me. I tried. :( Though hope video tutorials also help too for slow learners. :3 Anyways I hope both tutorials help either way. 👍 PS if someone is nervous about testing the roms in Ship2. I would HIGHLY SUGGEST testing it in PJ64 before EXTRACTING the ASSETS for Ship2. But guarantee they work. :) ^_^

**Comment by briaguya0** [comment]
i'm going to go ahead and close this out for now as there are tools available for extracting roms from the collectors edition iso. that being said it might be nice to come up with some decent documentation for doing the extraction.
