### ISSUE TITLE
Description of the bug

### ISSUE THREAD

**Issue by Arathok** [HarbourMasters/2ship2harkinian#552]
Getting a CRC not maching a known good rom. Can this behaviour be prevented? What is a known good rom. Without source links its a bit of a lost cause. I tried 5 different rom pages.
Is the problem because i am using an european rom?

**Comment by pancake-byte** [comment]
This is not a bug. The only supported versions of the game are NTSC.

We also do not condone software piracy in any way shape or form, so don't expect any help beyond this.  Source your ROMs legally by dumping them from a cartridge or disc that you own.

**Comment by jmfergeau** [comment]
Will non-NTSC versions (e.g european) be supported in the future, like for SoH?

**Comment by denaunistic** [comment]
> Will non-NTSC versions (e.g european) be supported in the future, like for SoH?

yes, it is just a matter of time
