### ISSUE TITLE
Duplicate steam virtual gamepads detected on Steam Deck - can't edit/remove one, causing input clashes

### ISSUE THREAD

**Issue by Bluejinjo** [HarbourMasters/2ship2harkinian#557]
- [*] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [*] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:

On my Steam Deck, the game is detecting two steam virtual gamepads (SDL 0) in the controller configuration menu (pics attached).

![20240528005826_1](https://github.com/HarbourMasters/2ship2harkinian/assets/163579567/9ce17dec-b810-45f4-ad8f-3de31790c33c)
![20240528005832_1](https://github.com/HarbourMasters/2ship2harkinian/assets/163579567/7f83d466-a8b9-45ee-9b34-aea14799738e)

I'm launching the game in game mode and using the same controller layout as OoT SoH. The controller in blue is persistant and won't stay removed after re-launching the game and i also can't change the button values either. The controller in red is the one the game recognises when changing button mapping, but during gameplay, buttons from both are recognised.

This is causing input clashes and I have to manually remove the blue virtual gamepad every time I launch the game.

This issue doesn't exist in the controller config for OoT SoH.

### Expected behavior:

Only one steam virtual gamepad should be detected and in the case of removing one manually, for that to then stay removed upon re-launch.

### System Information:
- OS: Steam OS
- GFX Backend: OpenGL
- Game Version: 1.0.0
- Rom Version: N64 NTSC-U 1.0

**Comment by rehashedsalt** [comment]
This might be a wider Linux-affecting issue. I get the same thing with my Xbox controller on Fedora 40:

![image](https://github.com/HarbourMasters/2ship2harkinian/assets/12635110/38ed964e-8a16-4deb-b0cb-e12aa8f51b0c)
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/12635110/23164bbb-696d-40b7-9583-66d77cd1eb8b)

**Comment by Bluejinjo** [comment]
I've tried removing all references to the second device in the 2ship2harkinian.json file with no luck removing it in-game. The only thing I could do for now is to edit the button mapping in that file, so they both match each other and they're both set to what I want.

**Comment by briaguya0** [comment]
this should be fixed in Rika Bravo (1.0.1), if this is still an issue on that version (after clearing out all the mappings from `2ship2harkinian.json`) i can reopen this
