### ISSUE TITLE
Stars seem to be displaying incorrectly

### ISSUE THREAD

**Issue by Bluejinjo** [HarbourMasters/2ship2harkinian#570]
May be related to #492, but not sure.

### Description of the inaccuracy:

Stars in the sky are much more visible (bigger?) than they should be, they jitter and don't move smoothly when rotating the camera (which may be the issue raised in #492) and they appear to be much more saturated (pink stars looking red).

In comparison, Zelda64Recomp displays them differently, which looks accurate to original hardware.

To get a good comparison go into Termina field, they start to appear at 7:30pm.

**Comment by Archez** [comment]
The pinkish stars have been fixed by Rika Bravo (1.0.1).

Interpolation will be tracked by the other linked issue.
