### ISSUE TITLE
Modified controls are not being saved

### ISSUE THREAD

**Issue by warderkeeju** [HarbourMasters/2ship2harkinian#571]
- [ x ] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [ x ] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
After modifying the configuration of the controls and restarting the game, the controls are not being saved.  May be related to #557 and the other bugs when dealing with multiple controls being detected under Linux.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [ x ] Yes, here are the steps to reproduce the bug:

1. Customize controls under 2Ship2Harkinian Linux
2. Exit application
3. Re-open application, check for customized controls -- they have reverted to default.

### Expected behavior:
Customized controls should be saved.  They are not being saved.

### System Information:
- OS: SteamOS 3.5.19
- GFX Backend: OpenGL
- Game Version: 1.0.0
- Rom Version: 1.0 US (sha256 - EFB1365B3AE362604514C0F9A1A2D11F5DC8688BA5BE660A37DEBF5E3BE43F2B)

### Additional Information:
This is most likely related to the #557 where control pads are being duplicated.

**Comment by briaguya0** [comment]
going off the assumption this is related to the duplicate controller issue, i'm going to close this out as that should be fixed in Rika Bravo (1.0.1), if this is still an issue on that version (after clearing out all the mappings from `2ship2harkinian.json`) i can reopen this

**Comment by Ash-Hybrid** [comment]
this is happening to me as well, it also happens if your controller disconnects as well too. Which reminds me of a previous issue i once reported before the new version dropped, except when i did, i was using an Xbox One Controller, however now i am using a PS4 controller (as the Xbox One Controller requires batteries + i lack a good micro USB cable.
