### ISSUE TITLE
Giant cutscene putting me in termina field instead of finishing the cutscene

### ISSUE THREAD

**Issue by bluexephops** [HarbourMasters/2ship2harkinian#577]
- [ x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x ] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:

When entering the clock tower and playing oath to order, the giant cutscene incorrectly fails to finish and link is spawned in the cutscene version of termina field
### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [ x] Yes, here are the steps to reproduce the bug:

1. Go to the clock tower on day 3
2. go through the skull kid dialogue
3. as soon as you regain control press the button your ocarina is on and play oath
4. watch the cutscene and before it ends you regain control of link
### Expected behavior:

The cutscene should continue and you should be placed on the moon after all the cutscenes finish.
### Screenshots or videos:

https://www.youtube.com/watch?v=Qz2LOn8vKus 
### System Information:
- OS: Windows 11
- GFX Backend: DirectX
- Game Version: Rika Alfa
- Rom Version: USA 1.0

**Comment by thegreatzoidberg** [comment]
Did you have Skip Story Cutscenes on?  I got the warp with it on but didn't with it off.

**Comment by bluexephops** [comment]
> Did you have Skip Story Cutscenes on? I got the warp with it on but didn't with it off.

No I originally had it on but I turned it off for further testing and it still happened

**Comment by Archez** [comment]
Fix is available in Rika Charlie 1.0.2
