### ISSUE TITLE
.Srm save files dont work

### ISSUE THREAD

**Issue by PiotrStuff** [HarbourMasters/2ship2harkinian#583]
title says it all

**Comment by inspectredc** [comment]
Hi! Please could you provide us with more information on your save. A good way for us to solve this would be to share it so we can test, and let us know where/what tool the save came from so we can see if we have issues with other .srm files from this source.

**Comment by garrettjoecox** [comment]
Additionally, please try removing any spaces/special characters from the file path before dragging it in. That's known to cause issues

**Comment by PiotrStuff** [comment]
changing the name worked, thank you
