### ISSUE TITLE
Enhancement: 3DS Song of Double Time Behavior

### ISSUE THREAD

**Issue by Dumbledork01** [HarbourMasters/2ship2harkinian#598]
Hey ya'll, great work on this decomp project!

I wanted to put this feature request out there since this is one of the only features from the 3DS port that was actually good.
I know ya'll have the developer tools already that allows selecting the current time (somewhere in SaveEditor.cpp), but I think an enhancement that allows the player to choose the time of day from a menu (or from the clock on the HUD itself) would be super cool. I'm guessing this would have to allow for either the text based clock or for the graphic clock to work though... (but maybe letting the user temporarily modify the time of day in this menu and then restore it if they cancel out would accomplish the same effect).

I figure the branch at line 5815 of z_message.c could contain some of this behavior alongside any code introduced in the enhancements section of the code. 
I'd be fine with trying to implement this myself if ya'll are busy on randomizer content, other enhancements, and stuff like that! I've been looking through the code and I think I have a few ideas of where I would start.

I mainly wanted to put this request out there in case someone was already working on it so no one else (like me) tried to implement it and got in the way haha.

(Feel free to resolve this if this was the wrong place to put this)

**Comment by garrettjoecox** [comment]
This is for sure planned, I think I am the only one who has begun looking into it, but I'm also swamped with other things so don't wait for me if you want to take a crack at it yourself.

After some investigation, my plan was to re-use the same patterns that the banker and bomber code input use, with text boxes that allow you to change the numbers with the analog stick.

All that said, going to convert this to a discussion, to keep our issues section limited to bugs. If you have any questions/problems feel free to ask for help in the #2s2h-development channel in discord!
