### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by lopenator** [HarbourMasters/2ship2harkinian#623]
First off this is amazing. Awesome work! I have been playing on lineage OS on my switch. Docked works great except for audio. I get no audio when playing with the switch docked. Audio works when in handheld mode. Everything else works great!

**Comment by McBedtime** [comment]
hi, the android port is unofficial and isn't maintained in this repo
You'll want to bring this issue up at https://github.com/Waterdish/2ship2harkinian-Android/ or the thread for the Android port in the 2s2h-threads forum in the discord server

**Comment by louist103** [comment]
Closing. Not in scope of the main repo as this is an Android port issue.
