### ISSUE TITLE
Reproducible crash when hover over graphic settings while in game when opened via steam (linux)

### ISSUE THREAD

**Issue by metronidazole** [HarbourMasters/2ship2harkinian#639]
### Description of the crash:
When i try to access the graphics settings anytime after starting the game (not including intro/save selection screen), the game will crash

### Can you reproduce? If so please list the steps:
1. Start 2s2h via steam 
- e.g. add a non-steam game, then run it
- i've set the steam overlay to DISABLED
2. Open a save
3. F1 to open settings
4. Move mouse and hover over graphic settings (underneath audio settings)

### Screenshots or videos:
None

### Logs:
[crash.log](https://github.com/user-attachments/files/15523965/crash.log)

### System Information:
- OS: Arch Linux
- GFX Backend: OpenGL
- Game Version: 1.0.1
- Rom Version: USA 1.0 (md5sum 2a0a8acb61538235bc1094d297fb6556)

### Additional Information:
Only occurs when 2s2h is opened via steam. Running 2s2h outside of steam will not reproduce the crash.

The crash traceback is slightly different for each crash.

**Comment by briaguya0** [comment]
what DE? do you have anything in the steam launch options for the game? do you have anything configured for steam compatibility (such as steam linux runtime)? could you share your `2ship2harkinian.json` file?

**Comment by metronidazole** [comment]
KDE Plasma 6.0.4
No launch options
Yes, all apps I run via steam use the steam runtime libraries. I don't have anything else configured.
[2ship2harkinian.json](https://github.com/user-attachments/files/15524187/2ship2harkinian.json)

**Comment by briaguya0** [comment]
interesting, i wasn't able to get it to run when using the steam linux runtime at all, i got a `AppImages require FUSE to run.` error

with the "Force the use of a specific Steam Play compatibility tool" box unchecked, however, it worked for me and i was unable to reproduce the issue

**Comment by metronidazole** [comment]
Oh this is with running the binary directly from compiling the source from the 1.0.1 release.

**Comment by briaguya0** [comment]
> Oh this is with running the binary directly from compiling the source from the 1.0.1 release.

ah, not sure why your *exact* issue would be a problem but i can see why that would cause issues. you're linking against your system libraries that way (with arch that means really new stuff), and the steam linux runtime is based on older stuff. since you've built the binary specifically for *your* system, you're better off not using the steam linux runtime at all

**Comment by metronidazole** [comment]
Good point, will try to disable it. Thanks
