### ISSUE TITLE
Wierdshot Crash when HESS/Wierdshot crash prevention is enabled.

### ISSUE THREAD

**Issue by kAuFish** [HarbourMasters/2ship2harkinian#645]
### Description of the crash:
Failed a wierdshot input, game crashed. Did it twice today, pretty sure I just didn't untarget Z fast enough.

### Can you reproduce? If so please list the steps:
- [ X] No, I cannot reproduce this crash
- [ ] Yes, here are the steps to reproduce the crash:

 sorry it's not very helpful but this is a visual of the frame the game crashed.
![image](https://github.com/HarbourMasters/2ship2harkinian/assets/38706312/bbc22392-4b3e-4164-90ff-2e7b856a75db)

### Logs:
[2 Ship 2 Harkinian.log](https://github.com/user-attachments/files/15526243/2.Ship.2.Harkinian.log)

### System Information:
- OS: Windows 11
- GFX Backend: OpenGL
- Game Version: 1.0
- Rom Version:  N64 USA release

### Additional Information:

Yes, I did make sure I had HESS crash fix enabled for both times. Playing on the 1.0 release, didn't see this get fixed in the patch notes but thought I'd share. I'm updating to the newer version now.

**Comment by sardonix** [comment]
Yo can you send me the settings file I don't know how to change renderer

**Comment by Malkierian** [comment]
> Yo can you send me the settings file I don't know how to change renderer

Don't hijack other issues for your question asked in your own.

**Comment by louist103** [comment]
Fixed by #710. For whatever reason GH didn't auto close this.
