### ISSUE TITLE
Cannot reset camera to follow mode when Goron rolling in spiked mode with free look enabled

### ISSUE THREAD

**Issue by jordanbtucker** [HarbourMasters/2ship2harkinian#649]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
Goron rolling with free look enabled is problematic with a controller because the camera does not follow Link. Since most players have their A button set to one of the four buttons on the right, and their camera set to the right analog stick, it's difficult to move the camera while holding the A button. Thankfully, you can tap the Z button, either before you begin your Goron roll or while rolling, to switch the camera into follow mode. However, switching to follow mode does not work once Link has sprouted spikes and has begun consuming magic. If the camera was switched to follow mode, by pressing the Z button, before the spikes appear, then the camera will stay in follow mode until the free look camera is moved, typically by moving the right analog stick. However, if the camera is ever put into free look mode either before or while the spikes are out, then pressing Z will not switch the camera back into follow mode.

Update: The same thing happens when Zora swimming. It's not possible to put the camera into follow mode once you've started Zora swimming. You must stop swimming, press the Z button, then begin swimming again without moving the camera.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

1. Enable Free Look.
2. Move the camera, and do not press Z.
3. Begin Goron rolling.
4. Press Z before the spikes appear.
5. Note that the camera switches to follow mode.
6. Move the camera to put it back into free look mode.
7. Continue Goron rolling until the spikes appear.
8. Press Z.
9. Note that the camera does not switch to follow mode.

### Expected behavior:
It should be possible to put the camera into follow mode by pressing Z while Goron rolling at any time.

### System Information:
- OS: Windows
- GFX Backend: DirectX
- Game Version: 04e5ac449d81b3875f68234226132e1fdd28f27e
- Rom Version: 1.0 U

**Comment by briaguya0** [comment]
it looks like recomp handles this by switching back to follow mode when the spikes appear, i think my personal preference would be to not force the camera back into follow mode and make pressing z work

**Comment by jordanbtucker** [comment]
Either that, or have a setting to let the player decide.

**Comment by cplaster** [comment]
I had the same issue with Goron Rolling and Zora Swimming (and to a lesser degree, Deku Gliding). I want free-look cam for pretty much everything except for these activities since its just hard to control, and its a pain to manually toggle it in the menu.

For my own personal build, I fixed this by adding the M1 and M2 modifier buttons from SoH back into the controller config, and just hardcoding the M1 button to toggle the free-look camera on and off. Feels a bit better to me than hitting Z to realign the camera. Not sure this is the ideal solution though.

**Comment by inspectredc** [comment]
The fix made in the PR that addresses this issue makes pressing Z effectively have the same effect as what you describe
