### ISSUE TITLE
OTR not found 

### ISSUE THREAD

**Issue by Ivanchuti** [HarbourMasters/2ship2harkinian#651]
After installing and decompiling the ROMs, this message appears that the file was not found, and the game opens but the screen freezes. The program needs a force quit. 

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this crash
- [x] Yes, here are the steps to reproduce the crash: Open the executable and then this message appears.

### Screenshots or videos:
![Captura de pantalla 2024-06-03 162319](https://github.com/HarbourMasters/2ship2harkinian/assets/171421506/2b45d761-3113-45bc-bc95-ec54e922d5f9)
![Captura de pantalla 2024-06-03 174416](https://github.com/HarbourMasters/2ship2harkinian/assets/171421506/3f7964f3-c406-477f-8f24-501eabd9809a)

### System Information:
- OS: Windows 10
- GFX Backend: DirectX 11
- Game Version: 1.0.1
- Rom Version: USA (1.0)

I also tried to change the name of the file path if there's any issue and it didn't work.

**Comment by garrettjoecox** [comment]
This might be an issue with special characters in your file path, you have `Iván`, could you try moving it somewhere else?

**Comment by Ivanchuti** [comment]
I moved it to another file path and also happens.

![Captura de pantalla 2024-06-03 170911](https://github.com/HarbourMasters/2ship2harkinian/assets/171421506/d6bfc1a5-1a54-4bc0-aa62-327535526711)

**Comment by garrettjoecox** [comment]
oh, it looks like you are missing the `2ship.otr`, which should be included in the download. Did you extract the entire download zip?

**Comment by Ivanchuti** [comment]
In the download zip of version 1.0.1, there isn't any OTR file.

![Captura de pantalla 2024-06-03 172218](https://github.com/HarbourMasters/2ship2harkinian/assets/171421506/1f96aad3-76b7-4c6b-a84e-6e70dd1702a8)

**Comment by garrettjoecox** [comment]
Appologies, we just recently switched from `otr` to `o2r`. The `2ship.o2r` is what you are looking for. It's recommended to always extract _everything_ from the downloads when you install

**Comment by Ivanchuti** [comment]
Okay, but then what I have to do with the O2R file?

**Comment by garrettjoecox** [comment]
It just needs to be present when you run the 2ship executable, in the same directory

**Comment by Ivanchuti** [comment]
Also with the O2R file, the message still appears.

![Captura de pantalla 2024-06-03 174218](https://github.com/HarbourMasters/2ship2harkinian/assets/171421506/16225e13-f7b4-4d74-bff0-64ee899139c4)

**Comment by Malkierian** [comment]
There may still be a special character in your file path. Try moving the Ship2 folder to the root of your C drive. If that doesn't work, you might have to delete mm.o2r and re-extract it from your ROM.

**Comment by Ivanchuti** [comment]
After moving to the root of the C drive, it works. Thanks for the help @garrettjoecox and @Malkierian :) 

![Captura de pantalla 2024-06-03 180000](https://github.com/HarbourMasters/2ship2harkinian/assets/171421506/e1000325-d21c-45fa-ae2d-a0b90386d8e4)
