### ISSUE TITLE
Description of the bug

### ISSUE THREAD

**Issue by m9henri** [HarbourMasters/2ship2harkinian#657]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [ ] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
The ladder in pirate fortress glitched out at the upper part

### Can you reproduce? If so please list the steps:
- [ ] Yes, here are the steps to reproduce the bug:
1. Go to pirate fortress.
2. Climb up the ladder before the telescope.
3. See the bug

### Expected behavior:
It shouldn't glitch out like that.

### Screenshots or videos:
![Bild_2024-06-04_030317464](https://github.com/HarbourMasters/2ship2harkinian/assets/97912678/b82f3d07-bf01-435a-a48e-97fe02da4ca5)

### System Information:
- OS: Windows 11
- GFX Backend: DirectX
- Game Version: 1.0.1
- Rom Version: 1.0

**Comment by inspectredc** [comment]
Closing as this is a result of the same issue as #475
