### ISSUE TITLE
Songs not registering as played

### ISSUE THREAD

**Issue by JeffGessas** [HarbourMasters/2ship2harkinian#667]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
I played without issue up to the first temple but then could not proceed because the song of awakening was not registering as played, even when input correctly on the little pedestal. After some fooling around I discovered that the Song of Soaring or Song of Awakening do not work with free camera controls bound to my right stick. Restoring default controls and using the right stick as a C-stick does cause the game to recognize the songs. Song of Time and Song of Healing work either way. Both songs were learnable and I can play them successfully in the pause menu but playing them in game does not trigger the effects except with default controls. I promise I was playing them correctly with my alt bindings.

Edit: as a workaround, I bound my keyboard arrow keys as additional c-buttons. They work with the free camera enabled (the songs trigger), but the alt c-bindings on my controller still do not trigger the songs. I use a switch pro controller with the following binds:
C-up = L
C-left = Y
C-Down = X
C-Right = R

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:
At least for me, it has to do with whether the controls utilize the right stick for camera or C-operations. 

### Screenshots or videos:

Here is the song with alt controls (not working): https://streamable.com/ccsfdt
And here is the song with default controls (working): https://streamable.com/inx4ry

### System Information:
- OS: Win 10
- GFX Backend: DirectX 11
- Game Version: Unsure, downloaded this week.
- Rom Version: Legend of Zelda, The - Majora's Mask (U) [!]

**Comment by OtherBlue** [comment]
Hey!
Seems your controls when you leave the right stick to camera have the same button assigned to C-Up and L

L is the "Cancel Song" button, so that's why the songs aren't being recognized

**Comment by JeffGessas** [comment]
> Hey! Seems your controls when you leave the right stick to camera have the same button assigned to C-Up and L
> 
> L is the "Cancel Song" button, so that's why the songs aren't being recognized

This was the problem. I'm an idiot. I did not know that L was the cancel song button! I always cancelled with B. Thanks!

**Comment by OtherBlue** [comment]
> > Hey! Seems your controls when you leave the right stick to camera have the same button assigned to C-Up and L
> > L is the "Cancel Song" button, so that's why the songs aren't being recognized
> 
> This was the problem. I'm an idiot. I did not know that L was the cancel song button! I always cancelled with B. Thanks!

Yeah, I mean B is cancel as in "Stop playing the instrument" while what L does is "Ignore any songs being played"
Probably to allow you to freestyle a bit

Z and R also affect notes being played in a way that stops song recognition

**Comment by JeffGessas** [comment]
> > > Hey! Seems your controls when you leave the right stick to camera have the same button assigned to C-Up and L
> > > L is the "Cancel Song" button, so that's why the songs aren't being recognized
> > 
> > 
> > This was the problem. I'm an idiot. I did not know that L was the cancel song button! I always cancelled with B. Thanks!
> 
> Yeah, I mean B is cancel as in "Stop playing the instrument" while what L does is "Ignore any songs being played" Probably to allow you to freestyle a bit
> 
> Z and R also affect notes being played in a way that stops song recognition

I never knew that. Thanks! I'll mark as completed but leave this up for others who maybe don't know.
