### ISSUE TITLE
Japas' improvisation fails on his own

### ISSUE THREAD

**Issue by KhoTeru** [HarbourMasters/2ship2harkinian#680]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
When improvising along Japas, the prompt for completing the melody cancels itself immediately.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:
1. Go to Zora Hall, and to Japas' room
2. Pull out the Ocarina (guitar) while standing next to Japas
3. After Japas plays his part of the melody, the prompt fails instantly

### Expected behavior:
The game should let you play the guitar / finish the improvisation

### Screenshots or videos:

https://github.com/HarbourMasters/2ship2harkinian/assets/36055140/4b6357f6-e384-46f8-9e70-837df88a3d5b

### System Information:
- OS: Arch Linux 6.9.3.arch1-1 
- GFX Backend: OpenGL
- Game Version: Rika Bravo 1.0.1
- Rom Version: USA 1.0

**Comment by louist103** [comment]
~~This seems to only happen on Linux.~~ To make things even worse, it only happens on release mode on Linux

**Comment by LSeelig** [comment]
How can I workaround this? Only thing I can think of is using my save with the windows version through wine then returning to Linux.

**Comment by Malkierian** [comment]
Just ignore it for now. It's not required to get the reward nor 100% the save.

**Comment by Archez** [comment]
Fix is available in Satoko Charlie 1.1.2
