### ISSUE TITLE
"Incorrect ROM file ; No valid ROMs were provided"

### ISSUE THREAD

**Issue by byjove01** [HarbourMasters/2ship2harkinian#681]
- [X] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
It simply doesn't recognize my game ROM and tell me it's an invalid one while it perfectly plays on emulators.

### Can you reproduce? If so please list the steps:
1. Install the .appimage
2. Copy the game ROM
3. Run the .appimage
4. See the bug

### Screenshots or videos:
https://i.imgur.com/TjYTY4I.png

### System Information:
- OS: Arch Linux kernel 6.9.3-arch1-1
- GFX Backend: OpenGL
- Game Version: 1.1
- Rom Version: Majora's Mask (PAL, France)

**Comment by OtherBlue** [comment]
Hi!
2Ship2Harkinian only supports NTSC-U 1.0 or GC ROMs at the moment, so this isn't a bug.

**Comment by byjove01** [comment]
Argh. I hope it'll be soon available for PAL ROMs.
