### ISSUE TITLE
2Ship2Harkinian has weird slow down issues

### ISSUE THREAD

**Issue by Mystical891** [HarbourMasters/2ship2harkinian#691]
- [ ] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [ ] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
When playing on Windows for a good while, the game will suddenly have a massive slowdown that last forever.

### Expected behavior:
When playing the game, it should run like normal all the time.

### System Information:
- OS: Windows 10, 19045.4529
- GFX Backend: DirectX
- Game Version: V1.0.1
- Rom Version: US V1.0

**Comment by RaynorArkenbout** [comment]
Seconded!

**Comment by MeatGlacier** [comment]
Same issue here. It's not normal "the PC can't handle it" slowdown, either--it almost feels like the game logic (pre-extrapolation to extra framerate) is being slowed down, somehow? The game is clearly still rendering at a very high framerate--100 fps, in my case--but is visibly and audibly experiencing slowdown and "chugging," if that makes any sense. Very odd.

I experienced it within the first cycle (towards the end of Night 1), which prevented me from finishing said cycle and thus being able to save and quit to test whether or not it persists after loading an affected save file.

**Comment by githubshizzler** [comment]
Same issue here,

OS Windows 10 22H2 Build 19045.4651
GFX Backend: DirectX
Game Version: V1.0.2
Rom Version: US V1.0

Graphics adjustment: 60 fps
After starting the game for the first time and gone through the 'Deku' Cycle I got to learn the Song of Healing. 
Then the slowdown started. It's an 'steady' slowdown (audio also stutters enormously)

I've managed to save at an owl statue. The reset option does nothing anymore. I have to close soh and reopen it. 
Then everything works as normal. This is only the second time I used 2s2h so I cant say it will slow down next time.

**Comment by Malkierian** [comment]
This has been fixed in the repository, further corroborating reports are not necessary.

**Comment by Archez** [comment]
This slowdown fix has been released starting with Satoko 1.1.x

**Comment by Mystical891** [comment]
Hey, sorry it took so long for me to respond, but I played the latest version of 2Ship2Harkinian, and the slowdown issue seem to have gotten worse when I started playing. Not sure if it’s my PC that’s outdated now, but it didn’t seem to fix the issue.
