### ISSUE TITLE
Setting an Area as cleared in the save editor Locks the dungeon if it requires a Song

### ISSUE THREAD

**Issue by smashbro596** [HarbourMasters/2ship2harkinian#703]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
=The Save Editors "area clear" function bugs woodfall and great bay rendering their dungeons inaccessible.

### Can you reproduce? If so please list the steps:
- [x] Yes, here are the steps to reproduce the bug:

-1. Go to... Save editor on a new cycle
-2. Do this...Check "woodfall clear" or "great bay clear"
-3. See the bug: woodfall remains sunk and the turtle that takes you to great bay isn't active. playing the required song does nothing

### Expected behavior:

Woodfall and Great bay temples should be accessible

### System Information:
- OS:Windows 11
- GFX Backend: OpenGL,
- Game Version:Nightly
- Rom Version: Majora's mask (U) 1.0

**Comment by balloondude2** [comment]
Playing Sonata at Woodfall sets WEEKEVENTREG_20_01. 

Playing Bossa for Lulu sets WEEKEVENTREG_53_20 and WEEKEVENTREG_93_08. 

I think 53_20 sets the turtle and 93_08 determines whether to play a long or short version of the cutscene on subsequent cycles.

**Comment by louist103** [comment]
Another one that didn't auto close.
