### ISSUE TITLE
[General Bug] Deku mask and Deku Link have broken UV wrapping when in Termina Field Musical Stones grotto

### ISSUE THREAD

**Issue by Dahleben** [HarbourMasters/2ship2harkinian#705]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

### Expected behavior:
The Deku mask and Deku link should have the correct UV wrapping.

### Screenshots or videos:
here is  Deku link having the right wrapping outside the grotto
<img width="1680" alt="Screen Shot 2024-06-21 at 4 31 03 PM" src="https://github.com/HarbourMasters/2ship2harkinian/assets/161896201/218a2b7a-c7b1-4e1c-9802-8173291413d8">

Here is the UV wrapping in the grotto
<img width="1680" alt="Screen Shot 2024-06-21 at 4 21 45 PM" src="https://github.com/HarbourMasters/2ship2harkinian/assets/161896201/092a0131-8acd-44f0-8ed1-45d67c9470fe">

### System Information:
- OS: MacOS Monterey 12.5.1
- GFX Backend: Metal
- Game Version: Develop
- Rom Version: Any

**Comment by Archez** [comment]
Worth mentioning that this is only happening on the develop branch, not in the official Rika release.

It's due to the recent color combiner changes in LUS.
