### ISSUE TITLE
Description of the crash

### ISSUE THREAD

**Issue by Bamahutt** [HarbourMasters/2ship2harkinian#715]
### Description of the crash:
I was just watching the end credits of the game with all mask collected and the game crash on the Deku king scene.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this crash
- [ Y ] Yes, here are the steps to reproduce the crash:

### Logs:
[2 Ship 2 Harkinian.log](https://github.com/user-attachments/files/15964445/2.Ship.2.Harkinian.log)

### System Information:
- OS: Windows 10 pro
- GFX Backend: OpenGL
- Game Version:1.0.0.0
- Rom Version: any

**Comment by Archez** [comment]
Hi, this issue was already fixed by #601 and available in the [1.0.1 Rika Bravo release](https://github.com/HarbourMasters/2ship2harkinian/releases/tag/1.0.1).
