### ISSUE TITLE
No O2R/ROM files?

### ISSUE THREAD

**Issue by Underplayer1** [HarbourMasters/2ship2harkinian#742]
- [X] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [X] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
I don't know if those files are supposed to come with the installation or not, but it says I don't have any. If the files aren't supposed to come with, could somebody please tell me where to download one?
### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [X] Yes, here are the steps to reproduce the bug:

1. Just open the file without an O2R or ROM file
2. See the bug

### Device Information
- OS: ChromeOS
- I dont know anything else

**Comment by Malkierian** [comment]
They aren't provided with the download, and you don't download the ROM, you dump it from your own physical copy, then put it in the directory for it to extract the assets and put them in an O2R. See the [dumping guide](https://www.shipofharkinian.com/setup-guide/dump-guide)

Also, I'm pretty sure ChromeOS isn't supported, or even if it technically is, Chromebooks are so weak you probably won't get much out of it.
