### ISSUE TITLE
Custom assets not working

### ISSUE THREAD

**Issue by jonahtavzies** [HarbourMasters/2ship2harkinian#745]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
The custom assets do not load, leaving you with the vanilla assets.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

### System Information:
- OS:
- GFX Backend: Metal, **OpenG**, or DirectX
- Game Version:
- Game Version:
- Rom Version:

**Comment by balloondude2** [comment]
Have you pressed Tab to toggle the alternate assets?

**Comment by Archez** [comment]
@jonahtavzies Can you confirm the above, that pressing Tab will toggle/enable the alternate assets?

**Comment by Archez** [comment]
Closing this issue as stale. New releases for 2Ship have improved custom asset support, and an exposed toggle in the UI menus for enabling alternate assets. Feel free to reopen if you still have issues.
