### ISSUE TITLE
`Incorrect ROM file - No valid ROMs were provided` (Verified Checksums)

### ISSUE THREAD

**Issue by ThisNekoGuy** [HarbourMasters/2ship2harkinian#751]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Can you reproduce? If so please list the steps:
- [x] Yes, here are the steps to reproduce the bug:

1. In my case, I compiled from source then had the following in a folder: `2s2h.sh 2s2h.elf gamecontrollerdb.txt 2s2hIcon.png`
2. `cd` to the folder containing these items via terminal (in my case, extracted from a zip archive)
3. Run `./2s2h.sh`
4. Encounter the strange behavior (on a first attempt, it may _look_ fine but you'll notice there's only a `mods` folder; subsequent attempts show the described behavior below)

### Expected behavior:

When running the Linux launch script, the Zenity pop-up claims that no valid rom was found and yet also attempts to generate an OTR in a seperate window regardless before eventually closing itself. Additionally, only the `mods` folder ever seems to get created and I never find the temp directory that's supposed to be made in `/tmp` despite having user permissions to do so.

### Screenshots or videos:

![screenshot](https://github.com/user-attachments/assets/f4e554a2-7edb-4dde-908e-a447a34baed7)

### System Information:
- OS: x86_64 Gentoo Linux 2.15 (Kernel 6.8.9)
- GFX Backend: OpenGL
- Game Version: 1.0.2 (LLVM Compiled 57cb5d2b5135a1cbc88ea9a4a94990fba291a11a)
- Rom Version: Both `NTSC-U` and `NTSC-U GC`

### Additional Information:

**Shell Output:**
```
cp: cannot stat '/tmp/assets-WRXTD/mm.o2r': No such file or directory
Warning: --window-icon is deprecated and will be removed in a future version of zenity; Treating as --icon.
Warning: --icon-name is deprecated and will be removed in a future version of zenity; Treating as --icon.

(zenity:19440): Gtk-WARNING **: 00:22:00.845: Unknown key gtk-modules in /home/neko/.config/gtk-4.0/settings.ini

(zenity:19444): Gtk-WARNING **: 00:22:00.847: Unknown key gtk-modules in /home/neko/.config/gtk-4.0/settings.ini

(zenity:19440): Adwaita-WARNING **: 00:22:00.909: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(zenity:19444): Adwaita-WARNING **: 00:22:00.910: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
```

**Comment by Archez** [comment]
Hi, are you still encountering this problem?

I think in this case what you are missing is the compiled `ZAPD.out` binary and the `assets` folder that contains all the xml files for extraction. Without this, the `2s2h.sh` script won't be able to generate an `mm.o2r` properly. The script is provided as-is and assumes that it is running from the appimage. You can refer to our CMake and CPack steps to see how we are bundling the final appimage.

**Comment by Archez** [comment]
I'm going to close this issue as stale. If you are still having trouble with whatever you are trying to do, feel free to reach out in our Discord for help.
