### ISSUE TITLE
Missing ROM file

### ISSUE THREAD

**Issue by Pitel** [HarbourMasters/2ship2harkinian#752]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
When starting the AppImage, I just get the dialog saying the ROM file is missing. But it's there, in the same directory. Named `majora.rom`. I've even checked it with https://2ship.equipment and it says it's a valid NTSC-U ROM.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

2. Download AppImage
3. Get the ROM and place it just next to the AppImage
4. Run AppImage

### Expected behavior:
No error, ROM gets extracet, game launched

### Screenshots or videos:

![Screenshot of the dialog](https://github.com/user-attachments/assets/e3af4b24-7ede-48e0-bff6-e72de9c59b28)

### System Information:
- OS: Ubuntu 23.10 or 24.04
- GFX Backend: OpenGL
- Game Version: 1.0.0-1.0.2 (it always happens)
- Rom Version: NTSC-U

### Additional Information:
The ROM file works with Zelda64Recomp.

```
drwxrwxr-x  3 pitel pitel 4,0K čec 25 16:59 .
drwxr-x--x 83 pitel pitel 4,0K čec 25 17:12 ..
-rw-rw-r--  2 pitel pitel  32M kvě 20 13:39 majora.rom
drwxrwxr-x  2 pitel pitel 4,0K čec 25 16:57 mods
-rw-r--r--  1 pitel pitel 3,5K čec 11 20:09 readme.txt
-rwxr-xr-x  1 pitel pitel 9,9M čec 11 20:09 2ship.appimage
```

**Comment by Malkierian** [comment]
Why did you give it a .rom extension? Pretty sure it's looking for .n64, .v64, or .z64, because those are N64 ROM extensions.

**Comment by Pitel** [comment]
🤦🏻‍♂️
