### ISSUE TITLE
C-Buttons all hidden and cannot retrieve.

### ISSUE THREAD

**Issue by mbaddah** [HarbourMasters/2ship2harkinian#763]
### Description of the bug:
C-buttons have gone missing and i'm unable to retrieve them? Odd because they were working fine before. I've tried resetting all the options and playing around with hud display options but nothing seems to work. 

I've also attached the save files. 

### Expected behavior:
C-buttons are all visible on the hud.

### Screenshots or videos:
![missing c-buttons](https://github.com/user-attachments/assets/aa863bd6-40a4-4e29-a7c4-7b75f1ce4ef1)
[saves.zip](https://github.com/user-attachments/files/16831286/saves.zip)

### System Information:
- OS: Windows 11
- GFX Backend: Vulcan
- Game Version: Charlie 1.0.2
- Rom Version: MM-US 1.0

**Comment by Malkierian** [comment]
Try changing the toggles for them to hidden and then back to moveable.

**Comment by mbaddah** [comment]
> Try changing the toggles for them to hidden and then back to moveable.

Unfortunately that didn't work 😞

**Comment by Archez** [comment]
I assume you also can't use any of the items assigned to the C-buttons?

Could you upload your save file here? It would be in the `saves` folder, with the number matching the slot you used on the file select menu.

**Comment by Malkierian** [comment]
I think they did, there's a "saves.zip" under the picture.

**Comment by Archez** [comment]
@mbaddah Alright, for your saves what you need to do is open up the Save Editor under the Developer Tools menu.
From here select the `Flags` tab and change the dropdown to `weekEventReg`, then scroll down to row 82 and uncheck the 4th box (tooltip will display `3`). This will re-enable your C-buttons.

![image](https://github.com/user-attachments/assets/c06b146d-8b12-4316-9388-7aab438ad4bb)

This most likely resulted from an autosave during the Swordsman school log slicing mini-game. Version 1.0.2 prevents auto saves from happening during mini-games, but if your save originally happened in an older version, then that would have carried over like you are experiencing.

**Comment by mbaddah** [comment]
That worked! Thanks @Archez :D
