### ISSUE TITLE
Convert save back to .bin for use in Zelda64Recomp

### ISSUE THREAD

**Issue by Furaihai** [HarbourMasters/2ship2harkinian#771]
I would like to be able to convert the .json save files from this game back to .bin files for use in other ports. Is there a way to convert save files the other direction for non-2S2H use?

### System Information:
- OS: Nobara Linux 39
- GFX Backend: OpenGL
- Game Version: Rika Charlie 1.0.2
- Rom Version: US

**Comment by Malkierian** [comment]
No, unless Recomp decides to make their own, as we probably won't ever do it.

**Comment by garrettjoecox** [comment]
Though it’s not in scope to be provided in the project itself, the code we use to convert from the binary to our JSON is available, and can likely be reversed with some effort 

https://github.com/HarbourMasters/2ship2harkinian/blob/develop/mm/2s2h/SaveManager/BinarySaveConverter.cpp
