### ISSUE TITLE
Map icons not working on Raspberry Pi OS (64 bit)

### ISSUE THREAD

**Issue by mimre25** [HarbourMasters/2ship2harkinian#774]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
The icons on the map are not working at all - sometimes I get some squares, but never really the yellow and red arrow.

![foo](https://github.com/user-attachments/assets/e5481409-ae23-4178-b0a9-19eba2aa4b94)

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

1. Build on Raspberry Pi Os 64 bit
2. Play the game
3. Buy a Map 

### System Information:
- OS: Linux rpi 6.6.47+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.47-1+rpt1 (2024-09-02) aarch64 GNU/Linux
- GFX Backend: OpenGL
- Ship Version: 1.0.2
- Game Version: US-1.0.0

**Comment by mimre25** [comment]
I've also noticed that 1 heart is always not showing.

**Comment by retropieuser** [comment]
I've noticed the hearts issue and also that the clock doesn't contain the hands moving either

This is with a RetroPie system but is built on the same RPI OS as you have above

**Comment by Archez** [comment]
When building for RPi, did you specify the `USE_OPENGLES` build flag for using OpenGL ES over standard OpenGL? `-DUSE_OPENGLES=1`

**Comment by retropieuser** [comment]
You're absolutely right, I rebuilt it with these functions and it works now, thank you for your help


    cmake -H. -B build-cmake -GNinja -DUSE_OPENGLES=1 -DCMAKE_BUILD_TYPE:STRING=Release

    cmake --build build-cmake --target ExtractAssets -j4

    cmake --build build-cmake -j4

**Comment by mimre25** [comment]
Worked like a charm:

```console
cmake -H. -Bbuild-cmake -GNinja -DUSE_OPENGLES=1
cmake --build build-cmake --target Generate2ShipOtr
cmake --build build-cmake 
```

**Comment by Malkierian** [comment]
Does that mean we can close this as resolved?

**Comment by mimre25** [comment]
yes! 

Just curious - what is the reason why OpenGLES is necessary for RPI, and is that mentioned in the build docs somewhere (and I just missed it)?

**Comment by Malkierian** [comment]
Because the RPi is built around ES. Mostly I think because of the processors used for them, they're designed for mobile and embedded applications.
