### ISSUE TITLE
[Vanilla Bug] Ikana Canyon Fairy Fountain color doesn't match its Stray Fairy color.

### ISSUE THREAD

**Issue by SuperBro64** [HarbourMasters/2ship2harkinian#787]
In the Japanese and US versions of vanilla MM, the Great Fairy's Fountain in Ikana Canyon has a green background, which doesn't match the yellow color of that fountain's Stray Fairies. According to The Cutting Room Floor (https://tcrf.net/The_Legend_of_Zelda:_Majora%27s_Mask/Program_Revision_Differences#Ikana_Fairy_Fountain_Coloring), this is due to "the environment not being set properly".

This bug was later fixed in the EU version so that the fountain color is yellow. Thus, since 2Ship currently only accepts the US versions of the game, perhaps an bug fix enhancement could be made to fix the color of the fountain?

Screenshot from TCRF showing the differences in the Ikana fountain color between versions:
![image](https://github.com/user-attachments/assets/582cd43d-c7b7-4176-a526-9dfe4982be4a)

Screenshot showing how the Ikana fountain currently looks in 2Ship:
![image](https://github.com/user-attachments/assets/c3bcccdb-86c3-40c8-8ae3-c150c04e98d3)

**Comment by garrettjoecox** [comment]
Interestingly, when you debug warp to that fairy fountain it has the correct color, if you leave and re-enter it has the broken color

<img width="1562" alt="Screenshot 2024-10-02 at 1 58 19 PM" src="https://github.com/user-attachments/assets/cc3a7c82-b865-4563-9256-bccc09a170a8">

**Comment by Archez** [comment]
Looks like having Stone Tower temple cleared or not is what causes this. If you load Ikana with the complete flag set, the sky in Ikana is "clear", then walking into the fountain will be yellow. But if the sky is "gloomy", and the clear flag is unset, then it's green.

If the flag is not set, then the "previous" weather mode is retained
```c
    if (gSaveContext.retainWeatherMode || (gSaveContext.respawnFlag != 0)) {
        switch ((u32)gWeatherMode) {
            case WEATHER_MODE_2:
                if (!CHECK_WEEKEVENTREG(WEEKEVENTREG_CLEARED_STONE_TOWER_TEMPLE)) {
```

**Comment by garrettjoecox** [comment]
> Looks like having Stone Tower temple cleared or not is what causes this. If you load Ikana with the complete flag set, the sky in Ikana is "clear", then walking into the fountain will be yellow. But if the sky is "gloomy", and the clear flag is unset, then it's green.

Glad we came to the same conclusion 😆 I imagine they have a more "correct" fix in the EU version but I PR'd a bandaid

**Comment by Archez** [comment]
Fix merged 👍
