### ISSUE TITLE
2ship.exe doesn't do anything.

### ISSUE THREAD

**Issue by KibaGbH** [HarbourMasters/2ship2harkinian#818]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
I got a Majora's Mask ROM and verified it with the website you provide. When I open the 2ship.exe and select my validated ROM, it doesn't do anything. Nothing happens, it just closes and that's it.

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

Basically just open any ROM I've found that's valid according to the rom checker provided.
1. Go to...
2. Do this...
3. See the bug
-->

### Expected behavior:

I'd expect it to open the game.

### Screenshots or videos:

![image](https://github.com/user-attachments/assets/d0d1e556-2d83-43d2-915c-ecd3097474cd)

Its after I select my ROM on this window that the bug happens.

### System Information:
- OS: Windows
- GFX Backend: DirectX
- Game Version: Unclear
- Rom Version: Unclear

### Additional Information:

The thing is, I've used this port before and it worked correctly. So I'm at a loss.

**Comment by mckinlee** [comment]
Just to confirm, the rom is in .z64 format correct?

**Comment by Malkierian** [comment]
Extension shouldn't matter, but I believe special characters in the ROM or exe file path do still.

**Comment by mckinlee** [comment]
It still needs to be a valid N64 format, .z64 being one of them. 

However, what Malk said is most likely the cause if its not the format.

**Comment by KibaGbH** [comment]
> Just to confirm, the rom is in .z64 format correct?

It's .n64, actually. I'll try to use a .z64 next

**Comment by Malkierian** [comment]
.n64, .v64, and .z64 are all valid N64 ROM formats (this is what I was referring to when I said extension shouldn't matter)

**Comment by KibaGbH** [comment]
> .n64, .v64, and .z64 are all valid N64 ROM formats (this is what I was referring to when I said extension shouldn't matter)

I changed the names of the files so they don't contain any special characters and it still doesn't work.

**Comment by Malkierian** [comment]
It's not just the names of the files, it's the entire path. For both the game and the ROM.

**Comment by KibaGbH** [comment]
> It's not just the names of the files, it's the entire path. For both the game and the ROM.

Yup, that did it. I changed the name of the entire folder it was in. Thanks!
