### ISSUE TITLE
"Move with left stick while in first person" allows moving in the Swamp Boat Tour

### ISSUE THREAD

**Issue by The-Brickler** [HarbourMasters/2ship2harkinian#823]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
The "Move with left stick while in first person" option allows link to move while in the swamp boat tour

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:
1. Enable the "Move with left stick while in first person" option
2. Go to southern swamp
3. Start the boat tour. (It also probably works with the witch archery minigame but I haven't cleared woodfall so I can't check)
4. Move the left stick around
5. See the bug

### Expected behavior:
Link should be prevented from moving during this scene

### Screenshots or videos:
https://github.com/user-attachments/assets/378e23c7-4865-4067-b4f4-4a7e35620338

### System Information:
- OS: Windows 11
- GFX Backend: DirectX
- Game Version: 1.0.2 Nov 2 20:48:59
- Rom Version: US 1.0

**Comment by Archez** [comment]
Fix is available in Satoko Charlie 1.1.2
