### ISSUE TITLE
Unable to interact with the new menu

### ISSUE THREAD

**Issue by ndb000** [HarbourMasters/2ship2harkinian#831]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:

The menu is completely unresponsive. After pressing Esc, i cannot click or navigate around it with neither a controller or keyboard.
### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

1. Open the menu
2. Try to interact with it
3. Keyboard/controller controls the game underneath

### Expected behavior:

Being able to navigate around the menu
### Screenshots or videos:

https://github.com/user-attachments/assets/af8fd660-2e1b-4621-b3a5-b0358dab251d

### System Information:
- OS: Arch Linux
- GFX Backend: OpenGL
- Game Version: Satoko Alfa 1.1.0
- Rom Version: MM-US 1.0

### Additional Information:

--

**Comment by garrettjoecox** [comment]
Could you try moving your 2ship2harkinian.json file elsewhere and see if a fresh configuration fixes it? If that does it, please send the broken configuration in here

**Comment by Malkierian** [comment]
Did you enable the controller navigation setting? It may not be on by default on PC platforms (and I'm still not sure if it should be).

**Comment by ndb000** [comment]
> Could you try moving your 2ship2harkinian.json file elsewhere and see if a fresh configuration fixes it? If that does it, please send the broken configuration in here

Doesn't fix it unfortunately

> Did you enable the controller navigation setting? It may not be on by default on PC platforms (and I'm still not sure if it should be).

I don't know how to enable it, i can't click on the option

**Comment by Malkierian** [comment]
You're in game mode, right? Game mode seems to continue to be a thorn in our sides for interaction support. Try running it in desktop mode (with the appimage directly) to enable it, then run in game mode again.

**Comment by ndb000** [comment]
i don't know what game mode/desktop mode is. Is it a steamdeck thing? because i'm not on steamdeck

**Comment by ndb000** [comment]
also, i don't know if this helps, but the legacy bar works fine

**Comment by Malkierian** [comment]
Wait, you can't click on the menu with the mouse?

**Comment by ndb000** [comment]
No, i can't. i shouldve made that more clear.

**Comment by Malkierian** [comment]
Would you download the build artifact from #837 and see if that changes anything for you?

**Comment by ndb000** [comment]
No, it's the same, can't click on it

**Comment by Malkierian** [comment]
Try with #844

**Comment by ndb000** [comment]
> Try with #844

That did it, awesome
