### ISSUE TITLE
Crash On Charged Sword Slash/Spin

### ISSUE THREAD

**Issue by wowitsjack** [HarbourMasters/2ship2harkinian#834]
### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this crash
- [x ] Yes, here are the steps to reproduce the crash:

Hold B

### System Information:
- OS: Steam Deck (HoloOS)
- GFX Backend: OpenGL
- Game Version: Latest
- Rom Version: Latest

### Additional Information:
Game unplayable

**Comment by Eblo** [comment]
Same issue as #827. It's fixed by #828, but in the meantime you can disable the two-handed sword magic enhancement to avoid the crash.
