### ISSUE TITLE
Volume Sliders Do Not Adjust Incrementally Between 0% and 100%

### ISSUE THREAD

**Issue by SalbugVR** [HarbourMasters/2ship2harkinian#854]
- [✅] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [✅] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
When adjusting the volume sliders, the percentage does not change incrementally and only jumps directly between 0% and 100%.

### Can you reproduce? If so please list the steps:
- [] No, I cannot reproduce this bug
- [✅] Yes, here are the steps to reproduce the bug:

1. Open Settings
2. Go to Audio
3. Adjust any of the volume sliders

### Expected behavior:
I expect the volume sliders to increment to any value between 0% and 100%.

### Screenshots or videos:

https://github.com/user-attachments/assets/9c9821f7-b433-4c48-880a-9cf26697fb08

### System Information:
- OS: Windows 11
- GFX Backend: Metal, OpenGL, or DirectX: DirectX
- Game Version: **Satoko Bravo 1.1.1**
- Rom Version: MM-US 1.0

### Additional Information:
**N/A**

**Comment by Malkierian** [comment]
Do none of the other sliders have that issue? Like the Internal Resolution slider in Graphics? Or Axis sensititivies in Camera Enhancements?

**Comment by Malkierian** [comment]
Check both the menubar and the new menu, if you would.

**Comment by Malkierian** [comment]
Actually, just try this build out when it's done building: https://github.com/Malkierian/2ship2harkinian/pull/4

**Comment by SalbugVR** [comment]
Yup. Works as intended on the test build.

https://github.com/user-attachments/assets/add0856d-4f2e-4b1f-b930-eae59c7e1555

**Comment by Malkierian** [comment]
Alright, now that I know what the issue was, I'll work on another build today with some diagnostic printing for you to run, if you're willing.

**Comment by SalbugVR** [comment]
Yeah, may be some time but I can check on it when I'm free.

**Comment by Malkierian** [comment]
Alright, PR'd the fix with #859. If you would download it when it's done building and verify I didn't undo the fix with some reversion management, I'd appreciate it.

**Comment by SalbugVR** [comment]
Sanity check reports all clear~ 👍

https://github.com/user-attachments/assets/85199eab-f8f2-4a62-8785-693ec3093281

**Comment by Malkierian** [comment]
Awesome.

**Comment by Archez** [comment]
Fix is available in Satoko Charlie 1.1.2
