### ISSUE TITLE
Bunny Hood Speed causing softlock during deku Game 

### ISSUE THREAD

**Issue by bluexephops** [HarbourMasters/2ship2harkinian#857]
- [X ] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [ X] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:

After paying 10 rupees to play the game, deku link gets stuck in a cutscene trying to enter the deku bulb.
### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [X ] Yes, here are the steps to reproduce the bug:

1.Go to Deku game next to Clock Town Fairy Fountain.
2.Pay 10 rupees to play while wearing persistent bunny hood
3. Bug occurs where he can't enter the bulb.
### Expected behavior:

Deku link enters the bulb so the game can start.
### Screenshots or videos:

https://github.com/user-attachments/assets/70d47a06-7a82-4723-91c9-5c5b0de601f7

### System Information:
- OS:Windows 11
- GFX Backend: Metal, OpenGL, or DirectX    - Direct X
- Game Version: Satoko Bravo
- Rom Version: US 1.0

**Comment by Archez** [comment]
Fix is available in Satoko Charlie 1.1.2
