### ISSUE TITLE
Persistent bunny hood causing time to not show during postman counting game.

### ISSUE THREAD

**Issue by bluexephops** [HarbourMasters/2ship2harkinian#858]
- [ X] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [ X] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:

When playing the postman game the timer disappears like it does without bunny hood.
### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [ X] Yes, here are the steps to reproduce the bug:

Go to post office
talk to postman to start game with persistent bunny hood on
wait for time to dissapear
### Expected behavior:

The time should work how it normally does with bunny hood on where the timer doesn't vanish.
### System Information:
- OS:Windows 11
- GFX Backend: Metal, OpenGL, or DirectX
DirectX
- Game Version: Satoko Bravo
- Rom Version: US 1.0

**Comment by Archez** [comment]
Fix is available in Satoko Charlie 1.1.2
