### ISSUE TITLE
Deku Guard vision particles visible at night

### ISSUE THREAD

**Issue by EpicGamerNaeNae** [HarbourMasters/2ship2harkinian#860]
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
The deku guards from the palace's vision particles are visible during the night

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:

1. Go to the deku palace rooms with the guards (left or right after the deku scrubs that block the entrance)
2. use the song of double time or sun's song (from the enhancements->songs menu) to change the time to night (or just walk in at night in the first place)
3. See vision particles coming from the guards

### Expected behavior:
Deku guard vision particles should always be invisible

### Screenshots or videos:

During the day (expected behavior):
![image](https://github.com/user-attachments/assets/2cedde6c-5d41-4b71-93aa-479023d35a3d)

During the night (bug):
![image](https://github.com/user-attachments/assets/c87d717e-3bed-4632-abcc-d250c05bd8c9)

### System Information:
- OS: Windows
- GFX Backend: OpenGL and DirectX
- Game Version: 1.1.1
- Rom Version: US N64

**Comment by Archez** [comment]
Hi, this is not an issue. This is how the game originally works. The dots will only display at night.

https://zelda.fandom.com/wiki/Deku_Palace#Inner_Palace_Garden

**Comment by EpicGamerNaeNae** [comment]
I wasn't aware that it was in the original game, but it seems like it was (at least considered by the 3D dev team as) a bug that was removed in the remake (which is probably why I thought it was a bug)
It would make sense to add the option to disable it as a fix/restoration type thing (but I guess that's more of a feature request so not for here)

3DS version footage of it "fixed":
https://youtu.be/2ohiw4Xj_mA?feature=shared&t=628

**Comment by Archez** [comment]
Ah I didn't realize 3ds version changed that. I could see adding an option for that.

**Comment by lscholte** [comment]
I put up a pull request to address this. I thought 3 options would make sense for this: never show them, only show them at night, and always show them.
